# Information about where the book exists on the web
repository:
  url: https://github.com/yecatstevir/teambrainiac
launch_buttons:
  colab_url: "https://colab.research.google.com/github/yecatstevir/teambrainiac"